### ISSUE TITLE
Merge into dbus-java?

### ISSUE THREAD

**Issue by xeruf** [hypfvieh/libmatthew#5]
As far as I know, you only use this library to get dbus-java working. So I think it would be reasonable to incorporate all the needed methods into dbus-java and then remove this, since nobody really knows what to do with it ^^

If you agree, I might also work on it. It would be helpful if I could get write access to dbus-java then, and be it on a separate branch, so I don't have to work on a fork.

**Comment by hypfvieh** [comment]
No I wont merge those two.

I use libmatthew because the original author did and I wanted a 'drop-in' replacement.

Also common distributions like debian/ubuntu already provide libmatthew via apt.
That has the advantage of being available to a whole bunch of end users without providing native compiled libraries for all the different architectures out there.

The library is only required because Java is still not capable of unix or raw sockets.

In theory one could also switch from this library to another which provides access to unix sockets.
But that would probably require a abstraction layer.

For me, the only reason taking care of libmatthew was to get it available on maven central and to provide some advanced way to load the library from different pathes.

So for any developer out there it should be fairly easy to setup a maven project using e.g. dbus-java and having all required dependencies ready to use.

**Comment by xeruf** [comment]
Ah it's in apt, good to know. That answers the question then.
